#
###################################
# Site wide configuration
####################################
#
title: Yi Xia
email: yxia921@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple blog to keep track of what interests me in life.
url: http://geeknerd.github.io # the base hostname & protocol for your site
#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Chicago
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Yi Xia
  avatar: avatar.jpg
  job: 
  bio: "Too young, too simple, sometimes naive."
  email: zourenyuan@gmail.com
  disqus-shortname: renyuanzblog
  twitter: alittlered3 #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: renyuanz #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
