#
###################################
# Site wide configuration
####################################
#
title: Yi Xia
email: yxia921@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple blog to keep track of what interests me in life.
url: http://geeknerd.github.io # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
markdown:    kramdown
highlighter: rouge
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "page/:num"

BASE_PATH : http://geeknerd.github.io
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
      coderay_line_numbers:      inline
      coderay_line_number_start: 1
 

#
###################################
# Jekyll configuration
####################################
#
owner:
  name: Yi Xia
  avatar: avatar.jpg
  bio: Too young, too simple, sometimes naive.
  email: yxia921@gmail.com
  disqus-shortname: geeknerd
  twitter: #username
  facebook: bao571 #username
  google:
    plus: YiXia571 #username
    analytics: UA-67656024-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: geeknerd #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: hiyixia #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: geeknerdlab #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
